openapi: '3.0.2'
info:
  title: Vearch API
  version: "3.5.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for sending dynamic records to the Vearch.
servers:
  - url: 'http://{VearchURL}'
    variables:
        VearchURL:
          default: 'localhost:9001'
    description: Vearch server

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []

paths:
  /servers:
    $ref: 'paths/cluster.yaml#/ListServer'
  /partitions:
    $ref: 'paths/cluster.yaml#/ListPartitions'
  /cluster/stats:
    $ref: 'paths/cluster.yaml#/Status'
  /cluster/health:
    $ref: 'paths/cluster.yaml#/Health'

  /dbs/{dbName}:
    $ref: 'paths/database.yaml#/DbsPath'
  /dbs:
    $ref: 'paths/database.yaml#/Dbs'
  /dbs/{dbName}/spaces:
    $ref: 'paths/space.yaml#/Spaces'
  /dbs/{dbName}/spaces/{spaceName}:
    $ref: 'paths/space.yaml#/Space'

  /document/upsert:
    $ref: 'paths/document.yaml#/Upsert'
  /document/delete:
    $ref: 'paths/document.yaml#/Delete'
  /document/search:
    $ref: 'paths/document.yaml#/Search'
  /document/query:
    $ref: 'paths/document.yaml#/Query'
